name: SecureFace
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - opencv
  - numpy
  - psycopg2
  - pip:
    - insightface==0.7.3
    - python-dotenv
    - faiss-cpu # Or faiss-gpu if you plan to use GPU
    - Faker
    # Installing retinaface separately due to dependency conflicts